# Generated by Django 5.2 on 2025-04-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSeek', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
