# Generated by Django 5.2 on 2025-04-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSeek', '0002_blog_blog_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_url',
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
